//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AK.Net.Dns {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AK.Net.Dns.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End has already been called on this operation..
        /// </summary>
        internal static string AsyncResultEndAlreadyCalled {
            get {
                return ResourceManager.GetString("AsyncResultEndAlreadyCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified &lt;character-string&gt; is too long..
        /// </summary>
        internal static string CharStringTooLong {
            get {
                return ResourceManager.GetString("CharStringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified collection must be readonly..
        /// </summary>
        internal static string CollectionMustBeReadonly {
            get {
                return ResourceManager.GetString("CollectionMustBeReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not assignable from {1}..
        /// </summary>
        internal static string ConfigurationTypeIsNotAssignableFrom {
            get {
                return ResourceManager.GetString("ConfigurationTypeIsNotAssignableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unble to read the DNS name as the maximum number of references ({0}) has been reached..
        /// </summary>
        internal static string DnsNameHasTooManyRefs {
            get {
                return ResourceManager.GetString("DnsNameHasTooManyRefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoder data does not contain a query message..
        /// </summary>
        internal static string DnsQueryExpected {
            get {
                return ResourceManager.GetString("DnsQueryExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DnsQuestion is already a member of this DnsQuestionCollection..
        /// </summary>
        internal static string DnsQuestionAlreadyAMember {
            get {
                return ResourceManager.GetString("DnsQuestionAlreadyAMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert the specified record to an IP address as it is not of type A or AAAA..
        /// </summary>
        internal static string DnsRecordMustBeAorAaaa {
            get {
                return ResourceManager.GetString("DnsRecordMustBeAorAaaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoder data does not contain a reply message..
        /// </summary>
        internal static string DnsReplyExpected {
            get {
                return ResourceManager.GetString("DnsReplyExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to answer query as the server responded with a negative response code.
        ///
        ///Question: {0}
        ///Response Code: {1}.
        /// </summary>
        internal static string DnsResolverNegativeResponseCodeReceived {
            get {
                return ResourceManager.GetString("DnsResolverNegativeResponseCodeReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during transport: &apos;{0}&apos;.
        /// </summary>
        internal static string DnsTransportFailed {
            get {
                return ResourceManager.GetString("DnsTransportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete the transport operation as the incoming message size ({0} bytes) exceeds the maximum size as specified in the configuration ({1} bytes)..
        /// </summary>
        internal static string DnsTransportIncomingMessageToLarge {
            get {
                return ResourceManager.GetString("DnsTransportIncomingMessageToLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete the transport operation as no endpoint replied..
        /// </summary>
        internal static string DnsTransportNoEndPointsReplied {
            get {
                return ResourceManager.GetString("DnsTransportNoEndPointsReplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete the transport operation as the incoming message is zero bytes in length..
        /// </summary>
        internal static string DnsTransportReceivedEmptyMessage {
            get {
                return ResourceManager.GetString("DnsTransportReceivedEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of the underlying data stream has been reached before all data needed for the current operation could be read..
        /// </summary>
        internal static string EndOfDnsStreamReached {
            get {
                return ResourceManager.GetString("EndOfDnsStreamReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected internal error occurred: {0}.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified async result does not belong to this operation..
        /// </summary>
        internal static string InvalidAsyncResult {
            get {
                return ResourceManager.GetString("InvalidAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to decode the DnsHeader from the specified reader as the format of the data is invalid..
        /// </summary>
        internal static string InvalidDnsHeaderFormat {
            get {
                return ResourceManager.GetString("InvalidDnsHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to decode the DnsMessage from the specified reader as the format of the data is invalid..
        /// </summary>
        internal static string InvalidDnsMessageFormat {
            get {
                return ResourceManager.GetString("InvalidDnsMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to decode the DnsQuestion from the specified reader as the format of the data is invalid..
        /// </summary>
        internal static string InvalidDnsQuestionFormat {
            get {
                return ResourceManager.GetString("InvalidDnsQuestionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an IPAddress of valid DNS name..
        /// </summary>
        internal static string MustBeAnIPAddressOrDnsName {
            get {
                return ResourceManager.GetString("MustBeAnIPAddressOrDnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an IPv4 address..
        /// </summary>
        internal static string MustBeAnIPv4Addr {
            get {
                return ResourceManager.GetString("MustBeAnIPv4Addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an IPv4 or IPv6 address..
        /// </summary>
        internal static string MustBeAnIPv4OrIPv6Addr {
            get {
                return ResourceManager.GetString("MustBeAnIPv4OrIPv6Addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an IPv6 address..
        /// </summary>
        internal static string MustBeAnIPv6Addr {
            get {
                return ResourceManager.GetString("MustBeAnIPv6Addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid DNS name..
        /// </summary>
        internal static string MustBeAValidDnsName {
            get {
                return ResourceManager.GetString("MustBeAValidDnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be an empty string..
        /// </summary>
        internal static string MustNotBeAnEmptyString {
            get {
                return ResourceManager.GetString("MustNotBeAnEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to concatenate an absolute DnsName with another DnsName..
        /// </summary>
        internal static string UnableToConcatToAbsoluteDnsName {
            get {
                return ResourceManager.GetString("UnableToConcatToAbsoluteDnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to make &apos;{0}&apos; relative to &apos;{1}&apos; as &apos;{0}&apos; is not a a sub-domain of &apos;{1}&apos;..
        /// </summary>
        internal static string UnableToMakeRelativeNotASubDomainOfName {
            get {
                return ResourceManager.GetString("UnableToMakeRelativeNotASubDomainOfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a supported or recognised DNS label name type..
        /// </summary>
        internal static string UnsupportedDnsNameLabelType {
            get {
                return ResourceManager.GetString("UnsupportedDnsNameLabelType", resourceCulture);
            }
        }
    }
}
